sudo: false
language: java
notifications:
  email: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install: wget https://gist.githubusercontent.com/Doridian/01cb63301fe4d022f533bd221e227970/raw/0771d2c50808b295abfbabe266be7368c3273974/settings.xml
  -O settings.bin
script: mvn deploy -DaltDeploymentRepository=deployment-repo-id::default::https://maven.doridian.net/repository/maven-snapshots/
  --settings settings.bin
env:
  global:
  - secure: jmhhSaZU7mC2fqNgKmW2lDlR2gaBdHuTxaQoE+cz4sXGmf4M2z7KR5FSNWUrMyUPH5W5+5uFFIVfPwPrXsOr0S4Sqe9vkAIXU+Lyv0QrFEBYe/5dYXacFsuGugIv6hH4qKUmvSDt1tCgFid7cZM0x+BExBC67CkjUR90VGtYoCKNHpszhn8CkdgJoZkRKFyM5KU/LCaMGtKHeSaGlxuLHCM65LTCoKbSCvR2ItG7dyEGZLb7WmGXyzDQ7sDIK7D+jOM7EafF1tNDzXMVknUaFyPV+4zQR0JlAgF9aC2T2tPRuiCGUlL4nDmhU7EImN10gN34UWnqYBgyBvmZrY44GUqgR+ICUPtA+tZD2uCqcnfShOhpu1dSRgP2e63WBQSGYQZr5D9uIIsa+NoszsZrPPEqf5HnMlgbw5zt54Pxd0MKYIzjkz8gUnqq0BAALq+vT3FVZ2FaBq1exV/r8xFv+9YEILFvUVjhZadULLyq/btHTrhM+Ekoo+TgBw7nXyn89vlQ5VgI2+8SI3NUYoxMtXdHvPKsaGSyZ3gxthkbKJuD8mZ25pmW0SsbFKltXATGT21YdraBrHYNJ6SV4xa4yw2enKa0Cnf+zoSmq3zwiA3PYfz6Xp3E3ZYjjjEfEjXN1Bk3JEYpmuEAb7zbna0FXxLqy3iIcQWRAYuFp8CrmZI=
  - secure: hibCsCiGXbLld4aqzfhIH1cyQwj/5Zg5aIpdoxGEXBysyse6lqLnLEcYJbQLVo4zzdKInHeBx4QqRDCexWnMD/J7yY6D71Z8UyF4XSyecqZRPBmjPt788KgWeZt4p0HF0cT8yX8lBIUUykgw/j5gTRaZUIHTI7bfEuVWE6L89iLzL+xeLeVGOxUa5L/7XfKjO5Izvz/BUPh0hwLZbcvC5aCAOjCw6nDi1888vRd6w0RzBimZPpMObB3W5vzoTjMD0/F4vUbrIpl9fSFYkmGHqAWx13hCCxoOLr3div5TJ4NQNwxiRt/+qnyQkYc5lZe6yr2hcoonhFt6nWyHuuh/yxn/tMBJX1ea0HiyglMO2eywkcWqBk0oKl9g3qRwuN9K74PMUwXZPI9A4r+U+DwwiAkCG9T6YMsVXUSkg2vZe2Ci4hxXtURwZY17PawEvnaBPvo7ckTjrT989yIlIuN/vdxy+YFPsnXMlHlAv1Zii3TJaKfGVx9LxPMG2XZLVvf4KJ/s6ytmzSniWijUu/9UvNQ6BRhvIrqHS7WdSVJFGumze6DHlHoyvdlPxyJJUmhTLPz/RBYueQgYvmksecEd2hLTqtnjzs7mwbz0KECgHLhOv2IUOB+1e3SqvqblMqSQ2nF34dhs1XNMzdi5tH1Q6LICN8bJPB2RHbNsEpS78WM=
